export const INCREMENT_COUNT ="INCREMENT_COUNT" 
export const DECREMENT_COUNT = "DECREMENT_COUNT"
export const ADD_COUNTER  = "ADD_COUNTER"
export const SUB_COUNTER = "SUB_COUNTER"

export const START_FETCHING_DATA = "START_FETCHING_DATA"

export const FETCHING_DATA_SUCCESS ="FETCHING_DATA_SUCCESS"

export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE"


export const FETCH_DATA_START_SAGA = "FETCH_DATA_START_SAGA"

export const FETCH_DATA_SUCCESS_SAGA = "FETCH_DATA_SUCCESS_SAGA"

export const FETCH_DATA_FAILURE_SAGA = "FETCH_DATA_FAILURE_SAGA"

export const FETCH_DATA_SAGA ="FETCH_DATA_SAGA"

export const GET_RESTAURENT_DATA = "GET_RESTAURENT_DATA" 


export const ADD_RESTAURENT_DATA="ADD_RESTAURENT_DATA"

export const REMOVE_RESTAURENT_DATA="REMOVE_RESTAURENT_DATA"

export const EDIT_RESTAURENT_DATA="EDIT_RESTAURENT_DATA"